### ISSUE TITLE
Default version of "kob install -env KOBman" command

### ISSUE THREAD

**Issue by EtricKombat-zz** [asa1997/KOBman#39]
We regret for the issue that you are facing, Thanks for helping us by raising an issue so that we can improve ourself to do the best.
Mark one of the issues given below with respect to the issue you are facing with:
- [ ] Issue facing with installation or setup of KOBman utility. 
- [x] Issue facing while running an environment.
- [ ] Issue facing while adding a new environment or new file.
- [ ] Other issues: please provide the issue in the comment box

____________________________________________________________________________________

### Please explain the Issue / Feature Request here:

https://github.com/hyperledgerkochi/KOBman/pull/186

____________________________________________________________________________________
### Please provide the necessary screenshots or documents regarding the issue:

![image](https://user-images.githubusercontent.com/33585301/92258301-3cefc980-eef4-11ea-980a-059c75d6c389.png)

issue still persists

**Comment by asa1997** [comment]
@EtricKombat  It says version does not exist because version T804 has not been added into the list.txt file
