### ISSUE TITLE
RF-1.0.0.1.4.1 - Uninstall functionaltiy - no parameter issue

### ISSUE THREAD

**Issue by EtricKombat-zz** [asa1997/KOBman#5]
# ISSUE

![image](https://user-images.githubusercontent.com/33585301/85377933-751f7700-b557-11ea-866e-07d434ab1a0e.png)

**Comment by panickervinod** [comment]
@asa1997  Why do need a cat command, can't we check if file exists and is not empty

**Comment by asa1997** [comment]
@panickervinod @EtricKombat  The issue has been resolved.
