### ISSUE TITLE
RF-1.0.1.4.2 - Test script for uninstall functionality - unexpected output

### ISSUE THREAD

**Issue by EtricKombat-zz** [asa1997/KOBman#8]
# Error snapshot

![image](https://user-images.githubusercontent.com/33585301/85706760-26f9a780-b700-11ea-9227-2d76fc7c2ce0.png)

**Comment by asa1997** [comment]
This issue has been resolved with the pull request https://github.com/hyperledgerkochi/KOBman/pull/104, hence closing.
